language: php
php:
- 7.2
before_script:
  - composer install
script: phpunit tests
deploy:
    provider: heroku
    app: project1-travis-michael
    on: master
    skin_cleanup: true
    api_key:
        secure: ypupJLXkNsiR3q7zPOwzAh08n0qsCID64zLM6vTqBIK57Kz2mLk2ZbqjehNysNSb+RirE+LTzjMCtwk5+CPTNmxhvIA6QU4fY3bRB1VcB0Bw8SjXg0WClw888fV70Viz5BX1B0WuwwbPHqHUy+DUFrGWMG78SDkPwS5S+5K0WetIA4+RED3IwFtc9hstZULD3yc4kNXgKgwS4sHO9VhNhd52yvlGsC21EhfLO5ifDxptot+WkgvdxcLeGZrl3I0PLziui4VY4YYg8hfHaqbZ1Ilye+3JfK7JuyGvdBxrPV4K0Zn4Nsed32eTNghpRdVAQGg6SXuNsKJRzwi94CFWQIyP/A42Ot1KjzYY+IqTA+oQcZPYXOaqg7WhYED43WwGZRG2ikq77Ty9JAIeh3Jqd/HiNGR8eHxKSvG15DKlIt0d8M4FaFbwvOE6jwsQwspdDMzUoKuVEwfUqM9Ch1AR8cETxhs9eixro3FiC1OKSHgIQxER7ZvhK3pKuT+4G9KISeIewOoIdlzgh5Dh+g4s3DlNLhLnimtK75ueoOK6QvhIeMAiB9purI3QCZPAGwdIEa/q5ORPXFKJNkceQjF0uDezdGU7Yk8jp2nFuwCjNdlf99RyG6ged0RsHBIOkNGVTwy3eJcinavH0dQq+CPpv1ftp51S6i7dGqG907QWkDk=
